[build]
  publish = "frontend/build"
  command = "npm run build"

# Proxy /api requests to the backend service hosted at api.rasagnavarma.com
[[redirects]]
  from = "/api/*"
  to = "https://api.rasagnavarma.com/:splat"
  status = 200
  force = true
